
name: Build modules

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: micropython/micropython
        path: micropython
        ref: v1.20.0
    - name: Install Python dependencies
      run: pip install emlearn scikit-learn
    - name: Setup MicroPython X86
      working-directory: micropython
      run: source tools/ci.sh && ci_unix_32bit_setup && ci_unix_standard_build
    - name: Build module x64
      run: make -C eml_trees/ dist ARCH=x64 V=1 MPY_DIR=../micropython
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          dist
    - name: Setup MicroPython ARM
      working-directory: micropython
      run: source tools/ci.sh && ci_rp2_setup
    - name: Build module armv6m
      run: make -C eml_trees/ dist ARCH=armv6m V=1 MPY_DIR=../micropython
    - name: Build module armv7m
      run: make -C eml_trees/ dist ARCH=armv7m V=1 MPY_DIR=../micropython

